Mem sort
db-benchmarks/ui pull request #8
Opened 2022-06-16 21:09 UTC by djklim87

2022-06-17 05:52 UTC, sanikolaev commented
Let's render this as markdown or at least as plain text to preserve the ends of line:
<img width="1221" alt="image" src="https://user-images.githubusercontent.com/28719845/174231664-0ccb0fbd-bf52-4eab-95ae-cf00eae59418.png">

---

When some engine is selected let's highlight it:
<img width="709" alt="image" src="https://user-images.githubusercontent.com/28719845/174231816-a4a8b1ec-06a3-422c-b7e3-528ac0128302.png">

with a border or a shadow or whatever else, so it's clear it's active now.

---

Let's show not `n`, but `n/m` where `n` is the number of active engine_types and `m` is the total number.

<img width="656" alt="image" src="https://user-images.githubusercontent.com/28719845/174232671-17d36686-01fb-46f3-81a2-8501e5b2587c.png">

like this:

<img width="1185" alt="image" src="https://user-images.githubusercontent.com/28719845/174232992-f5aacd88-0a03-4fe1-b1b9-e24152bdc812.png">

2022-06-19 12:37 UTC, djklim87 commented
> order or a shadow or whatever else, so it's clear it's acti

done

2022-06-22 03:32 UTC, sanikolaev requested changes
Few minor things are left and we are all set to merge the PR.

2022-06-22 03:32 UTC, sanikolaev commented on backend/Dockerfile
> +    && echo "xdebug.client_host = host.docker.internal" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
Since you have docker-compose-dev.yml let's add another Dockerfile for dev, so the prod one is lighter and faster.

2022-06-22 03:32 UTC, sanikolaev commented on readme.md
> +To local development we have `docker-compose-dev.yml` there enabled x-debug in php for breakpoints using, and changed default Nginx listen port to `8080`
```suggestion
# Development environment

There is `docker-compose-dev.yml` that you can use for easier development and maintenance. It enables php x-debug for breakpoints and changes default Nginx port to `8080`
```

2022-06-22 03:32 UTC, sanikolaev commented on readme.md
> +Just run it from `localhost:8080/api`
```suggestion
`index.php` is already mounted as a volume into the docker container, so you don't need to rebuild it after each change in the backend code.
It's available on `localhost:8080/api`
```

2022-06-22 03:32 UTC, sanikolaev commented on readme.md
> +Add backend API URL `VUE_APP_API_URL="http://localhost:8080"` to `/frontend/.env` and run `vue-cli-service serve`. That's all you need for local frontend development
```suggestion
#### Frontend

Add backend API URL via env. var.  `VUE_APP_API_URL="http://localhost:8080"` to `/frontend/.env` and run `vue-cli-service serve`. That's all you need for local frontend development.
```

2022-06-22 03:33 UTC, sanikolaev commented on backend/Dockerfile
> +    && echo "xdebug.client_host = host.docker.internal" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
Never mind. I see the prod docker-compose doesn't build at all and just uses an image.

2022-06-22 03:36 UTC, sanikolaev commented on frontend/src/App.vue
> +            us on GitHub⭐</a></h1>
```suggestion
          <h1 align="center" style="padding-top: 10px;"><a href="https://github.com/db-benchmarks/db-benchmarks">⭐Star us on GitHub⭐</a></h1>
```

2022-06-22 03:40 UTC, merged